# https://docs.cloud.google.com/text-to-speech/docs/gemini-tts#available_languages
language_to_bcp47 = {
    "Arabic (Egypt)": "ar-EG",
    "Bangla (Bangladesh)": "bn-BD",
    "Dutch (Netherlands)": "nl-NL",
    "English (India)": "en-IN",
    "English (United States)": "en-US",
    "French (France)": "fr-FR",
    "German (Germany)": "de-DE",
    "Hindi (India)": "hi-IN",
    "Indonesian (Indonesia)": "id-ID",
    "Italian (Italy)": "it-IT",
    "Japanese (Japan)": "ja-JP",
    "Korean (South Korea)": "ko-KR",
    "Marathi (India)": "mr-IN",
    "Polish (Poland)": "pl-PL",
    "Portuguese (Brazil)": "pt-BR",
    "Romanian (Romania)": "ro-RO",
    "Russian (Russia)": "ru-RU",
    "Spanish (Spain)": "es-ES",
    "Tamil (India)": "ta-IN",
    "Telugu (India)": "te-IN",
    "Thai (Thailand)": "th-TH",
    "Turkish (Turkey)": "tr-TR",
    "Ukrainian (Ukraine)": "uk-UA",
    "Vietnamese (Vietnam)": "vi-VN",
    "Afrikaans (South Africa)": "af-ZA",
    "Albanian (Albania)": "sq-AL",
    "Amharic (Ethiopia)": "am-ET",
    "Arabic (World)": "ar-001",
    "Armenian (Armenia)": "hy-AM",
    "Azerbaijani (Azerbaijan)": "az-AZ",
    "Basque (Spain)": "eu-ES",
    "Belarusian (Belarus)": "be-BY",
    "Bulgarian (Bulgaria)": "bg-BG",
    "Burmese (Myanmar)": "my-MM",
    "Catalan (Spain)": "ca-ES",
    "Cebuano (Philippines)": "ceb-PH",
    "Chinese, Mandarin (China)": "cmn-CN",
    "Chinese, Mandarin (Taiwan)": "cmn-tw",
    "Croatian (Croatia)": "hr-HR",
    "Czech (Czech Republic)": "cs-CZ",
    "Danish (Denmark)": "da-DK",
    "English (Australia)": "en-AU",
    "English (United Kingdom)": "en-GB",
    "Estonian (Estonia)": "et-EE",
    "Filipino (Philippines)": "fil-PH",
    "Finnish (Finland)": "fi-FI",
    "French (Canada)": "fr-CA",
    "Galician (Spain)": "gl-ES",
    "Georgian (Georgia)": "ka-GE",
    "Greek (Greece)": "el-GR",
    "Gujarati (India)": "gu-IN",
    "Haitian Creole (Haiti)": "ht-HT",
    "Hebrew (Israel)": "he-IL",
    "Hungarian (Hungary)": "hu-HU",
    "Icelandic (Iceland)": "is-IS",
    "Javanese (Java)": "jv-JV",
    "Kannada (India)": "kn-IN",
    "Konkani (India)": "kok-IN",
    "Lao (Laos)": "lo-LA",
    "Latin (Vatican City)": "la-VA",
    "Latvian (Latvia)": "lv-LV",
    "Lithuanian (Lithuania)": "lt-LT",
    "Luxembourgish (Luxembourg)": "lb-LU",
    "Macedonian (North Macedonia)": "mk-MK",
    "Maithili (India)": "mai-IN",
    "Malagasy (Madagascar)": "mg-MG",
    "Malay (Malaysia)": "ms-MY",
    "Malayalam (India)": "ml-IN",
    "Mongolian (Mongolia)": "mn-MN",
    "Nepali (Nepal)": "ne-NP",
    "Norwegian, Bokmål (Norway)": "nb-NO",
    "Norwegian, Nynorsk (Norway)": "nn-NO",
    "Odia (India)": "or-IN",
    "Pashto (Afghanistan)": "ps-AF",
    "Persian (Iran)": "fa-IR",
    "Portuguese (Portugal)": "pt-PT",
    "Punjabi (India)": "pa-IN",
    "Serbian (Serbia)": "sr-RS",
    "Sindhi (India)": "sd-IN",
    "Sinhala (Sri Lanka)": "si-LK",
    "Slovak (Slovakia)": "sk-SK",
    "Slovenian (Slovenia)": "sl-SI",
    "Spanish (Latin America)": "es-419",
    "Spanish (Mexico)": "es-MX",
    "Swahili (Kenya)": "sw-KE",
    "Swedish (Sweden)": "sv-SE",
    "Urdu (Pakistan)": "ur-PK",
}
